CREATE OR REPLACE FUNCTION FUNC_PRODUCT_EXIST_AI()
 RETURNS trigger AS $$

 DECLARE COUNT_STOCK INTEGER;

BEGIN

    SELECT COUNT(*) INTO COUNT_STOCK FROM TB_STOCK WHERE ID_PRODUCT = NEW.ID_PRODUCT;

    IF COUNT_STOCK > 0 THEN
        UPDATE TB_STOCK SET
            QTD = QTD + (NEW.QTD * -1),
            UNITARY_VALUE = NEW.UNITARY_VALUE
        WHERE ID_PRODUCT = NEW.ID_PRODUCT;

    END IF;

    RETURN NULL;
END;
$$
LANGUAGE 'plpgsql';

DROP TRIGGER IF EXISTS TRG_PRODUCT_EXIST_AI ON PUBLIC.TB_PRODUCT_EXIST;

CREATE TRIGGER TRG_PRODUCT_EXIST_AI
AFTER INSERT ON TB_PRODUCT_EXIST
FOR EACH ROW EXECUTE PROCEDURE FUNC_PRODUCT_EXIST_AI();