CREATE TABLE IF NOT EXISTS TB_PRODUCT(
    ID BIGSERIAL PRIMARY KEY NOT NULL,
    ID_PROVIDER BIGINT NOT NULL REFERENCES TB_PROVIDER(ID),
    NAME CHARACTER VARYING(255) NOT NULL,
    MIN_STOCK INTEGER NOT NULL,
    MAX_STOCK INTEGER NOT NULL,
    STATUS BOOLEAN NOT NULL
);