CREATE TABLE IF NOT EXISTS TB_PRODUCT(
    ID BIGSERIAL PRIMARY KEY NOT NULL,
    NAME CHARACTER VARYING(255) NOT NULL,
    MIN_STOCK INTEGER NOT NULL,
    MAX_STOCK INTEGER NOT NULL,
    ACTIVE BOOLEAN NOT NULL DEFAULT TRUE
);