CREATE TABLE IF NOT EXISTS TB_STOCK(
    ID BIGSERIAL PRIMARY KEY NOT NULL,
    ID_PRODUCT BIGINT NOT NULL REFERENCES TB_PRODUCT(ID),
    QTD INTEGER NOT NULL,
    UNITARY_VALUE DECIMAL(9,2) NOT NULL
);