CREATE TABLE IF NOT EXISTS TB_PRODUCT_ENTRY(
    ID BIGSERIAL PRIMARY KEY NOT NULL,
    ID_PRODUCT BIGINT NOT NULL REFERENCES TB_PRODUCT(ID),
    QTD INTEGER NOT NULL,
    UNITARY_VALUE DECIMAL(9,2) NOT NULL,
    DATE_ENTRY TIMESTAMP WITHOUT TIME ZONE
);