CREATE TABLE IF NOT EXISTS TB_PRODUCT_INPUT(
    ID BIGSERIAL PRIMARY KEY NOT NULL,
    ID_PRODUCT BIGINT NOT NULL REFERENCES TB_PRODUCT(ID),
    QTD INTEGER NOT NULL,
    UNITARY_VALUE NUMERIC(9,2) NOT NULL,
    CREATED_AT TIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP NOT NULL
);