CREATE OR REPLACE FUNCTION FUNC_PRODUCT_ENTRY_AI()
 RETURNS trigger AS $$

 DECLARE COUNT_STOCK INTEGER;

BEGIN

    SELECT COUNT(*) INTO COUNT_STOCK FROM TB_STOCK WHERE ID_PRODUCT = NEW.ID_PRODUCT;

    IF COUNT_STOCK > 0 THEN
        UPDATE TB_STOCK SET
            QTD = QTD + NEW.QTD,
            UNITARY_VALUE = NEW.UNITARY_VALUE
        WHERE ID_PRODUCT = NEW.ID_PRODUCT;

    ELSE
        INSERT INTO TB_STOCK(ID_PRODUCT, QTD, UNITARY_VALUE) VALUES (NEW.ID_PRODUCT, NEW.QTD, NEW.UNITARY_VALUE);

    END IF;

    RETURN NULL;
END;
$$
LANGUAGE 'plpgsql';

DROP TRIGGER IF EXISTS TRG_PRODUCT_ENTRY_AI ON PUBLIC.TB_PRODUCT_ENTRY;

CREATE TRIGGER TRG_PRODUCT_ENTRY_AI
AFTER INSERT ON TB_PRODUCT_ENTRY
FOR EACH ROW EXECUTE PROCEDURE FUNC_PRODUCT_ENTRY_AI();