CREATE OR REPLACE PROCEDURE PRD_UPDATE_STOCK(ID_PRODUCT INTEGER, QTD_PURCHASED INTEGER, UNITARY_VALUE DECIMAL(9,2))
LANGUAGE plpgsql
AS $$

DECLARE COUNT_STOCK INTEGER;

BEGIN

SELECT COUNT(*) INTO COUNT_STOCK FROM TB_STOCK WHERE TB_STOCK.ID_PRODUCT = ID_PRODUCT;

IF COUNT_STOCK > 0 THEN
    UPDATE TB_STOCK SET TB_STOCK.QTD = TB_STOCK.QTD + QTD_PURCHASED, TB_STOCK.UNITARY_VALUE = UNITARY_VALUE
    WHERE TB_STOCK.ID_PRODUCT = ID_PRODUCT;

ELSE
    INSERT INTO TB_STOCK(ID_PRODUCT, QTD, UNITARY_VALUE) VALUES (ID_PRODUCT, QTD_PURCHASED, UNITARY_VALUE);

END IF;

END
$$;